version: 2
updates:
  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain Python dependencies in the application directory
  - package-ecosystem: "pip"
    directory: "/application"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "pip"
    directory: "/evaluation"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Maintain Docker dependencies in the dist/docker directory
  - package-ecosystem: "docker"
    directory: "/dist/docker"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
  - package-ecosystem: "docker"
    directory: "/evaluation"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
