services:

  mongod:
    image: mongodb/mongodb-community-server:latest
    restart: always
    entrypoint:
      - sh
      - -c
      - |
        openssl rand -base64 756 > /tmp/keyfile  && chown 101:101 /tmp/keyfile ;
        python3 /usr/local/bin/docker-entrypoint.py
    command: >-
         mongod
         --config /etc/mongod.conf
         --replSet rs0
    ports:
     - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongod.conf:/etc/mongod.conf:ro
    extra_hosts:
         - "host.docker.internal:host-gateway"
    networks:
         - search-community


  # you need to install additionnal package, take a look here : https://hub.docker.com/r/ollama/ollama
  # create directory ollama
  ollama:
    image: ollama/ollama:0.30.6
    restart: always
    ports:
     - 11434:11434
    volumes:
      - /data/ollama:/root/.ollama
    devices:
        - nvidia.com/gpu=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  llama-cpp-chat:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    container_name: llama-cpp-chat-server
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "8081:8080"
    volumes:
      - ${HOME:-~}/.cache/huggingface:/root/.cache/huggingface:z
      - ./model-config:/models-config
    ipc: host
    devices:
        - nvidia.com/gpu=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: >
      -hf Qwen/Qwen3-14B-GGUF:Q4_K_M
      --port 8080
      --host 0.0.0.0
      -c 40960
      -ngl 40
      --temp 1.0
      --top-p 0.95
      --top-k 40
      --min-p 0
      --cache-type-k q4_0
      --cache-type-v q4_0
      --jinja
      -n 32768
      --presence-penalty 2.0
      --repeat-penalty 1.0
      --no-context-shift
    networks:
      - search-community
    restart: unless-stopped

  llama-cpp-embeddings:
    image: ghcr.io/ggml-org/llama.cpp:server
    container_name: llama-cpp-embeddings-server
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - "8082:8080"
    volumes:
      - ${HOME:-~}/.cache/huggingface:/root/.cache/huggingface:z
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: >
      --hf-repo gpustack/bge-m3-GGUF
      --hf-file bge-m3-Q4_K_M.gguf
      --port 8080
      --host 0.0.0.0
      --embedding
      -c 8192
      -b 8192
      -ub 8192
    networks:
      - search-community
    restart: unless-stopped

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    container_name: litellm-proxy
    #network_mode: "host"
    ports:
     - 4000:4000
    volumes:
      - ./litellm-config.yaml:/app/config.yaml:ro
    command: [ "--config", "/app/config.yaml", "--port", "4000" ]
    depends_on:
      - llama-cpp-chat
      - llama-cpp-embeddings
    restart: unless-stopped
    networks:
      - search-community


  # chromadb:
  #   #image: chromadb/chroma:0.5.15
  #   image: chromadb/chroma:1.3.5
  #   restart: always
  #   ports:
  #    - 8000:8000

  # pgvector:
  #   image: pgvector/pgvector:pg18-trixie
  #   shm_size: 1g
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_PASSWORD: root

  # grafana:
  #   image: grafana/grafana-enterprise
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   environment:
  #     GF_INSTALL_PLUGINS: "https://github.com/meln5674/grafana-mongodb-community-plugin/releases/download/v0.2.0%2Brc5/meln5674-mongodb-community.zip;meln5674-mongodb-community"
  #     GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: meln5674-mongodb-community
  #   links:
  #     - "mongo:mongo"
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false

networks:
   search-community:
      name: search-community
