services:

  mongod:
    image: mongodb/mongodb-community-server:latest
    restart: always
    entrypoint:
      - sh 
      - -c
      - |
        openssl rand -base64 756 > /tmp/keyfile  && chown 101:101 /tmp/keyfile ;
        python3 /usr/local/bin/docker-entrypoint.py
    command: >-
         mongod
         --config /etc/mongod.conf
         --replSet rs0
    ports:
     - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongod.conf:/etc/mongod.conf:ro
    extra_hosts:
         - "host.docker.internal:host-gateway"
    networks:
         - search-community


  # you need to install additionnal package, take a look here : https://hub.docker.com/r/ollama/ollama
  # create directory ollama
  ollama:
    image: ollama/ollama
    restart: always
    ports:
     - 11434:11434
    volumes:
      - /data/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  chromadb:
    #image: chromadb/chroma:0.5.15
    image: chromadb/chroma:1.3.5
    restart: always
    ports:
     - 8000:8000
    
  pgvector:
    image: pgvector/pgvector:pg18-trixie
    shm_size: 1g
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root

  # grafana:
  #   image: grafana/grafana-enterprise
  #   restart: always
  #   ports:
  #     - 3000:3000
  #   environment:
  #     GF_INSTALL_PLUGINS: "https://github.com/meln5674/grafana-mongodb-community-plugin/releases/download/v0.2.0%2Brc5/meln5674-mongodb-community.zip;meln5674-mongodb-community"
  #     GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: meln5674-mongodb-community
  #   links:
  #     - "mongo:mongo"
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #     ME_CONFIG_BASICAUTH: false

networks:
   search-community:
      name: search-community